#!/bin/sh
# usage:
#         do_validate file.xml
#

# work-around for "como"
if [ ${HOST} = "como" ] ; then
  export PY="/cygdrive/c/Python25/python.exe"
else
  export PY="python"
fi

${PY}  ../utils/validate.py ../schema/all.sch $*
