#!/bin/sh
# usage:
#         do_validate file.xml
#
# work-around for cygwin
if expr match "`uname`" "CYGWIN.*"; then
  export PY="/cygdrive/c/Python25/python.exe"
else
  export PY="python"
fi
${PY}  ../utils/validate.py ../schema/all.sch $*
