NeXus: NeXus::Stream::Attr Class Reference
NeXus::Stream::Attr Class Reference
IOstream like interface
Serialisable attribute.
#include <NeXusStream.hpp>
Public Member Functions
Attr ()
template<typename NumT >
Attr (NumT &d)
template<typename NumT >
Attr (const NumT &d)
template<typename NumT >
Attr (const std::string &name, NumT &d)
template<typename NumT >
Attr (const std::string &name, const NumT &d)
Attr (const std::string &name, Attr &d)
Attr (const std::string &name, const Attr &d)
Attr (const Attr &a)
Attr & operator= (const Attr &a)
void setName (const std::string &name)
virtual void readFromFile (File &nf) const
virtual void writeToFile (File &nf) const
virtual ~Attr ()
Protected Attributes
HolderBase * m_holder
Detailed Description
Serialisable attribute.
Examples:
napi_test_cpp.cxx.
Definition at line 113 of file NeXusStream.hpp.
Constructor & Destructor Documentation
NeXus::Stream::Attr::Attr () inline
Definition at line 119 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::Attr::Attr (NumT & d) inline
Definition at line 121 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::Attr::Attr (const NumT & d) inline
Definition at line 123 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::Attr::Attr (const std::string & name, NumT & d) inline
Definition at line 125 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::Attr::Attr (const std::string & name, const NumT & d) inline
Definition at line 127 of file NeXusStream.hpp.
NeXus::Stream::Attr::Attr (const std::string & name, Attr & d) inline
Definition at line 128 of file NeXusStream.hpp.
References NeXus::Stream::HolderBase::clone(), and m_holder.
NeXus::Stream::Attr::Attr (const std::string & name, const Attr & d) inline
Definition at line 129 of file NeXusStream.hpp.
References NeXus::Stream::HolderBase::clone(), and m_holder.
NeXus::Stream::Attr::Attr (const Attr & a) inline
Definition at line 130 of file NeXusStream.hpp.
References NeXus::Stream::HolderBase::clone(), and m_holder.
virtual NeXus::Stream::Attr::~Attr () inline virtual
Definition at line 135 of file NeXusStream.hpp.
Member Function Documentation
Attr& NeXus::Stream::Attr::operator= (const Attr & a) inline
Definition at line 131 of file NeXusStream.hpp.
References NeXus::Stream::HolderBase::clone(), and m_holder.
virtual void NeXus::Stream::Attr::readFromFile (File & nf) const inline virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 133 of file NeXusStream.hpp.
void NeXus::Stream::Attr::setName (const std::string & name) inline
Definition at line 132 of file NeXusStream.hpp.
virtual void NeXus::Stream::Attr::writeToFile (File & nf) const inline virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 134 of file NeXusStream.hpp.
Member Data Documentation
HolderBase* NeXus::Stream::Attr::m_holder protected
Definition at line 116 of file NeXusStream.hpp.
Referenced by Attr(), and operator=().
The documentation for this class was generated from the following file:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp