NeXus: NeXus::Stream::HolderBase Class Reference
NeXus::Stream::HolderBase Class Reference abstract
Base class for serialisable named and typed parameter.
#include <NeXusStream.hpp>
Public Member Functions
HolderBase ()
HolderBase (const std::string &name)
void setName (const std::string &name)
std::string getName ()
virtual NXnumtype getType ()=0
virtual HolderBase * clone ()=0
virtual ~HolderBase ()
Public Member Functions inherited from NeXus::Stream::ISerialisable
virtual void readFromFile (File &nf) const =0
virtual void writeToFile (File &nf) const =0
Protected Attributes
std::string m_name
Detailed Description
Base class for serialisable named and typed parameter.
Definition at line 70 of file NeXusStream.hpp.
Constructor & Destructor Documentation
NeXus::Stream::HolderBase::HolderBase () inline
Definition at line 76 of file NeXusStream.hpp.
NeXus::Stream::HolderBase::HolderBase (const std::string & name)
Definition at line 50 of file NeXusStream.cpp.
virtual NeXus::Stream::HolderBase::~HolderBase () inline virtual
Definition at line 82 of file NeXusStream.hpp.
Member Function Documentation
virtual HolderBase* NeXus::Stream::HolderBase::clone () pure virtual
Implemented in NeXus::Stream::DataHolder< NumT >, and NeXus::Stream::AttrHolder< NumT >.
Referenced by NeXus::Stream::Attr::Attr(), NeXus::Stream::Data::Data(), NeXus::Stream::Attr::operator=(), and NeXus::Stream::Data::operator=().
std::string NeXus::Stream::HolderBase::getName () inline
Definition at line 79 of file NeXusStream.hpp.
Referenced by NeXus::Stream::Data::readFromFile(), and NeXus::Stream::Data::writeToFile().
virtual NXnumtype NeXus::Stream::HolderBase::getType () pure virtual
Implemented in NeXus::Stream::DataHolder< NumT >, NeXus::Stream::AttrHolder< NumT >, and NeXus::Stream::AttrHolder< NumT >.
void NeXus::Stream::HolderBase::setName (const std::string & name)
Definition at line 54 of file NeXusStream.cpp.
References m_name.
Member Data Documentation
std::string NeXus::Stream::HolderBase::m_name protected
Definition at line 73 of file NeXusStream.hpp.
Referenced by setName().
The documentation for this class was generated from the following files:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp
/isis/nexus_temp/bindings/cpp/NeXusStream.cpp