NeXus: NeXus::Stream::ObjectWithAttr Class Reference
NeXus::Stream::ObjectWithAttr Class Reference
Serialisable NeXus class with associated attributes.
#include <NeXusStream.hpp>
Public Member Functions
ObjectWithAttr (const std::string &attr1_name="", const Attr &attr1_value=Attr(), const std::string &attr2_name="", const Attr &attr2_value=Attr())
virtual void readFromFile (File &nf) const
virtual void writeToFile (File &nf) const
virtual ~ObjectWithAttr ()
Protected Member Functions
void processAttr (const std::string &attr1_name, const Attr &attr1_value, const std::string &attr2_name, const Attr &attr2_value)
Protected Attributes
std::list< Attr > m_attr
Detailed Description
Serialisable NeXus class with associated attributes.
Definition at line 141 of file NeXusStream.hpp.
Constructor & Destructor Documentation
NeXus::Stream::ObjectWithAttr::ObjectWithAttr (const std::string & attr1_name = "", const Attr & attr1_value = Attr(), const std::string & attr2_name = "", const Attr & attr2_value = Attr()) inline
Definition at line 160 of file NeXusStream.hpp.
virtual NeXus::Stream::ObjectWithAttr::~ObjectWithAttr () inline virtual
Definition at line 181 of file NeXusStream.hpp.
Member Function Documentation
void NeXus::Stream::ObjectWithAttr::processAttr (const std::string & attr1_name, const Attr & attr1_value, const std::string & attr2_name, const Attr & attr2_value) inline protected
Definition at line 146 of file NeXusStream.hpp.
virtual void NeXus::Stream::ObjectWithAttr::readFromFile (File & nf) const inline virtual
Implements NeXus::Stream::ISerialisable.
Reimplemented in NeXus::Stream::Data, and NeXus::Stream::Group.
Definition at line 165 of file NeXusStream.hpp.
Referenced by NeXus::Stream::Group::readFromFile(), and NeXus::Stream::Data::readFromFile().
virtual void NeXus::Stream::ObjectWithAttr::writeToFile (File & nf) const inline virtual
Implements NeXus::Stream::ISerialisable.
Reimplemented in NeXus::Stream::Data, and NeXus::Stream::Group.
Definition at line 173 of file NeXusStream.hpp.
Referenced by NeXus::Stream::Group::writeToFile(), and NeXus::Stream::Data::writeToFile().
Member Data Documentation
std::list<Attr> NeXus::Stream::ObjectWithAttr::m_attr protected
Definition at line 144 of file NeXusStream.hpp.
Referenced by NeXus::Stream::Data::readFromFile(), and NeXus::Stream::Data::writeToFile().
The documentation for this class was generated from the following file:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp