NeXus: NeXus::Stream::ISerialisable Class Reference
NeXus::Stream::ISerialisable Class Reference abstract
interface implemented by all serialisable NeXus components
#include <NeXusStream.hpp>
Public Member Functions
virtual void readFromFile (File &nf) const =0
virtual void writeToFile (File &nf) const =0
Detailed Description
interface implemented by all serialisable NeXus components
Definition at line 57 of file NeXusStream.hpp.
Member Function Documentation
virtual void NeXus::Stream::ISerialisable::readFromFile (File & nf) const pure virtual
Implemented in NeXus::Stream::Data, NeXus::Stream::DataHolder< NumT >, NeXus::Stream::Group, NeXus::Stream::ObjectWithAttr, NeXus::Stream::Attr, NeXus::Stream::AttrHolder< NumT >, and NeXus::Stream::AttrHolder< NumT >.
Referenced by NeXus::Stream::operator>>(), and NeXus::Stream::Data::readFromFile().
virtual void NeXus::Stream::ISerialisable::writeToFile (File & nf) const pure virtual
Implemented in NeXus::Stream::Data, NeXus::Stream::DataHolder< NumT >, NeXus::Stream::Group, NeXus::Stream::ObjectWithAttr, NeXus::Stream::Attr, and NeXus::Stream::AttrHolder< NumT >.
Referenced by NeXus::Stream::operator<<(), and NeXus::Stream::Data::writeToFile().
The documentation for this class was generated from the following file:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp