NeXus: NeXus::Stream::AttrHolder< NumT > Class Template Reference
NeXus::Stream::AttrHolder< NumT > Class Template Reference
Serialisable NeXus attribute.
#include <NeXusStream.hpp>
Public Member Functions
AttrHolder (const std::string &name, NumT &value)
AttrHolder (const std::string &name, const NumT &value)
AttrHolder (NumT &value)
AttrHolder (const NumT &value)
NXnumtype getType ()
virtual void readFromFile (File &nf) const
virtual void writeToFile (File &nf) const
AttrHolder * clone ()
virtual ~AttrHolder ()
template<>
NXnumtype getType ()
template<>
void readFromFile (File &nf) const
Public Member Functions inherited from NeXus::Stream::HolderBase
HolderBase ()
HolderBase (const std::string &name)
void setName (const std::string &name)
std::string getName ()
virtual ~HolderBase ()
Protected Member Functions
AttrHolder ()
AttrHolder (const std::string &name, const NumT *cv, NumT *v)
Protected Attributes
const NumT * m_c_value
NumT * m_value
Protected Attributes inherited from NeXus::Stream::HolderBase
std::string m_name
Detailed Description
template<typename NumT>
class NeXus::Stream::AttrHolder< NumT >
Serialisable NeXus attribute.
Definition at line 89 of file NeXusStream.hpp.
Constructor & Destructor Documentation
template<typename NumT> NeXus::Stream::AttrHolder< NumT >::AttrHolder () inline protected
Definition at line 94 of file NeXusStream.hpp.
template<typename NumT> NeXus::Stream::AttrHolder< NumT >::AttrHolder (const std::string & name, const NumT * cv, NumT * v) inline protected
Definition at line 95 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::AttrHolder< NumT >::AttrHolder (const std::string & name, NumT & value)
Definition at line 60 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::AttrHolder< NumT >::AttrHolder (const std::string & name, const NumT & value)
Definition at line 65 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::AttrHolder< NumT >::AttrHolder (NumT & value)
Definition at line 70 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::AttrHolder< NumT >::AttrHolder (const NumT & value)
Definition at line 75 of file NeXusStream.cpp.
template<typename NumT> virtual NeXus::Stream::AttrHolder< NumT >::~AttrHolder () inline virtual
Definition at line 106 of file NeXusStream.hpp.
Member Function Documentation
template<typename NumT> AttrHolder* NeXus::Stream::AttrHolder< NumT >::clone () inline virtual
Implements NeXus::Stream::HolderBase.
Definition at line 105 of file NeXusStream.hpp.
template<> NXnumtype NeXus::Stream::AttrHolder< std::string >::getType () virtual
Implements NeXus::Stream::HolderBase.
Definition at line 86 of file NeXusStream.cpp.
template<typename NumT > NXnumtype NeXus::Stream::AttrHolder< NumT >::getType () virtual
Implements NeXus::Stream::HolderBase.
Definition at line 80 of file NeXusStream.cpp.
template<> void NeXus::Stream::AttrHolder< std::string >::readFromFile (File & nf) const virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 92 of file NeXusStream.cpp.
References NeXus::File::getAttr().
template<typename NumT > void NeXus::Stream::AttrHolder< NumT >::readFromFile (File & nf) const virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 105 of file NeXusStream.cpp.
References NeXus::File::getAttr().
template<typename NumT > void NeXus::Stream::AttrHolder< NumT >::writeToFile (File & nf) const virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 118 of file NeXusStream.cpp.
References NeXus::File::putAttr().
Member Data Documentation
template<typename NumT> const NumT* NeXus::Stream::AttrHolder< NumT >::m_c_value protected
Definition at line 92 of file NeXusStream.hpp.
template<typename NumT> NumT* NeXus::Stream::AttrHolder< NumT >::m_value protected
Definition at line 93 of file NeXusStream.hpp.
The documentation for this class was generated from the following files:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp
/isis/nexus_temp/bindings/cpp/NeXusStream.cpp