NeXus: NeXus::Stream::DataHolder< NumT > Class Template Reference
NeXus::Stream::DataHolder< NumT > Class Template Reference
Serialisable NeXus data.
#include <NeXusStream.hpp>
Public Member Functions
DataHolder (const std::string &name)
DataHolder (const std::string &name, std::vector< NumT > &value)
DataHolder (const std::string &name, const std::vector< NumT > &value)
DataHolder (std::vector< NumT > &value)
DataHolder (const std::vector< NumT > &value)
NXnumtype getType ()
virtual void readFromFile (File &nf) const
virtual void writeToFile (File &nf) const
DataHolder * clone ()
virtual ~DataHolder ()
Public Member Functions inherited from NeXus::Stream::HolderBase
HolderBase ()
HolderBase (const std::string &name)
void setName (const std::string &name)
std::string getName ()
virtual ~HolderBase ()
Protected Member Functions
DataHolder ()
DataHolder (const std::string &name, const std::vector< NumT > *cv, std::vector< NumT > *v)
Protected Attributes
const std::vector< NumT > * m_c_value
std::vector< NumT > * m_value
Protected Attributes inherited from NeXus::Stream::HolderBase
std::string m_name
Detailed Description
template<typename NumT>
class NeXus::Stream::DataHolder< NumT >
Serialisable NeXus data.
Definition at line 220 of file NeXusStream.hpp.
Constructor & Destructor Documentation
template<typename NumT> NeXus::Stream::DataHolder< NumT >::DataHolder () inline protected
Definition at line 225 of file NeXusStream.hpp.
template<typename NumT> NeXus::Stream::DataHolder< NumT >::DataHolder (const std::string & name, const std::vector< NumT > * cv, std::vector< NumT > * v) inline protected
Definition at line 226 of file NeXusStream.hpp.
template<typename NumT > NeXus::Stream::DataHolder< NumT >::DataHolder (const std::string & name)
Definition at line 177 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::DataHolder< NumT >::DataHolder (const std::string & name, std::vector< NumT > & value)
Definition at line 172 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::DataHolder< NumT >::DataHolder (const std::string & name, const std::vector< NumT > & value)
Definition at line 182 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::DataHolder< NumT >::DataHolder (std::vector< NumT > & value)
Definition at line 187 of file NeXusStream.cpp.
template<typename NumT > NeXus::Stream::DataHolder< NumT >::DataHolder (const std::vector< NumT > & value)
Definition at line 192 of file NeXusStream.cpp.
template<typename NumT> virtual NeXus::Stream::DataHolder< NumT >::~DataHolder () inline virtual
Definition at line 238 of file NeXusStream.hpp.
Member Function Documentation
template<typename NumT> DataHolder* NeXus::Stream::DataHolder< NumT >::clone () inline virtual
Implements NeXus::Stream::HolderBase.
Definition at line 237 of file NeXusStream.hpp.
template<typename NumT> NXnumtype NeXus::Stream::DataHolder< NumT >::getType () inline virtual
Implements NeXus::Stream::HolderBase.
Definition at line 234 of file NeXusStream.hpp.
template<typename NumT > void NeXus::Stream::DataHolder< NumT >::readFromFile (File & nf) const virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 136 of file NeXusStream.cpp.
References NeXus::File::closeData(), NeXus::File::getData(), and NeXus::File::openData().
template<typename NumT > void NeXus::Stream::DataHolder< NumT >::writeToFile (File & nf) const virtual
Implements NeXus::Stream::ISerialisable.
Definition at line 155 of file NeXusStream.cpp.
References NeXus::File::writeData().
Member Data Documentation
template<typename NumT> const std::vector<NumT>* NeXus::Stream::DataHolder< NumT >::m_c_value protected
Definition at line 223 of file NeXusStream.hpp.
template<typename NumT> std::vector<NumT>* NeXus::Stream::DataHolder< NumT >::m_value protected
Definition at line 224 of file NeXusStream.hpp.
The documentation for this class was generated from the following files:
/isis/nexus_temp/bindings/cpp/NeXusStream.hpp
/isis/nexus_temp/bindings/cpp/NeXusStream.cpp