#!/bin/sh
set -o errexit

# jenkins job name
job_name="$1"

export PATH=/usr/local/bin:$PATH

if test -d build; then 
    rm -fr build
fi
mkdir build
cd build
cmake ..
make
make pdfdoc

cd manual

# publish
if test "${job_name}" = "master branch"; then
    cd source
    rm -fr /isis/www/nexus/doc/examples
    cp -fr examples /isis/www/nexus/doc
    cd ..

    rm -fr /isis/www/nexus/doc/html
    cp -fr html /isis/www/nexus/doc
    cp -f pdf/nexus.pdf /isis/www/nexus/doc/NeXusManual.pdf
    cd ..

    cp -f www/* /isis/www/nexus
fi

