NeXus: /isis/nexus_temp/src/napi.c File Reference
napi.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <stdarg.h>
#include <napi.h>
#include <napi_internal.h>
#include <nxconfig.h>
#include "nxstack.h"
#include "nx_stptok.h"
Macros
#define NXBADURL 0
#define NXFILE 1
#define LIBSEP ":"
#define PATHSEP "/"
#define THREAD_LOCAL __thread
#define LOCKED_CALL(__call) __call
#define NUL '\0'
Functions
int validNXName (const char *name, int allow_colon)
valid NeXus names
NXstatus NXsetcache (long newVal)
void NXIReportError (void *pData, char *string)
void NXReportError (char *string)
void NXMSetError (void *pData, void(*NewError)(void *pD, char *text))
void NXMSetTError (void *pData, void(*NewError)(void *pD, char *text))
ErrFunc NXMGetError ()
void NXMDisableErrorReporting ()
void NXMEnableErrorReporting ()
NXstatus NXopen (CONSTCHAR *userfilename, NXaccess am, NXhandle *gHandle)
NXstatus NXreopen (NXhandle pOrigHandle, NXhandle *pNewHandle)
NXstatus NXclose (NXhandle *fid)
NXstatus NXmakegroup (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass)
NXstatus NXopengroup (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass)
NXstatus NXclosegroup (NXhandle fid)
NXstatus NXmakedata (NXhandle fid, CONSTCHAR *name, int datatype, int rank, int dimensions[])
NXstatus NXmakedata64 (NXhandle fid, CONSTCHAR *name, int datatype, int rank, int64_t dimensions[])
NXstatus NXcompmakedata (NXhandle fid, CONSTCHAR *name, int datatype, int rank, int dimensions[], int compress_type, int chunk_size[])
NXstatus NXcompmakedata64 (NXhandle fid, CONSTCHAR *name, int datatype, int rank, int64_t dimensions[], int compress_type, int64_t chunk_size[])
NXstatus NXcompress (NXhandle fid, int compress_type)
NXstatus NXopendata (NXhandle fid, CONSTCHAR *name)
NXstatus NXclosedata (NXhandle fid)
NXstatus NXputdata (NXhandle fid, const void *data)
NXstatus NXputattr (NXhandle fid, CONSTCHAR *name, const void *data, int datalen, int iType)
NXstatus NXputslab (NXhandle fid, const void *data, const int iStart[], const int iSize[])
NXstatus NXputslab64 (NXhandle fid, const void *data, const int64_t iStart[], const int64_t iSize[])
NXstatus NXgetdataID (NXhandle fid, NXlink *sRes)
NXstatus NXmakelink (NXhandle fid, NXlink *sLink)
NXstatus NXmakenamedlink (NXhandle fid, CONSTCHAR *newname, NXlink *sLink)
NXstatus NXopensourcegroup (NXhandle fid)
NXstatus NXflush (NXhandle *pHandle)
NXstatus NXmalloc (void **data, int rank, const int dimensions[], int datatype)
NXstatus NXmalloc64 (void **data, int rank, const int64_t dimensions[], int datatype)
NXstatus NXfree (void **data)
NXstatus NXgetnextentry (NXhandle fid, NXname name, NXname nxclass, int *datatype)
char * nxitrim (char *str)
NXstatus NXgetdata (NXhandle fid, void *data)
NXstatus NXgetrawinfo64 (NXhandle fid, int *rank, int64_t dimension[], int *iType)
NXstatus NXgetrawinfo (NXhandle fid, int *rank, int dimension[], int *iType)
NXstatus NXgetinfo (NXhandle fid, int *rank, int dimension[], int *iType)
NXstatus NXgetinfo64 (NXhandle fid, int *rank, int64_t dimension[], int *iType)
NXstatus NXgetslab (NXhandle fid, void *data, const int iStart[], const int iSize[])
NXstatus NXgetslab64 (NXhandle fid, void *data, const int64_t iStart[], const int64_t iSize[])
NXstatus NXgetnextattr (NXhandle fileid, NXname pName, int *iLength, int *iType)
NXstatus NXgetattr (NXhandle fid, const char *name, void *data, int *datalen, int *iType)
NXstatus NXgetattrinfo (NXhandle fid, int *iN)
NXstatus NXgetgroupID (NXhandle fileid, NXlink *sRes)
NXstatus NXgetgroupinfo (NXhandle fid, int *iN, NXname pName, NXname pClass)
NXstatus NXsameID (NXhandle fileid, NXlink *pFirstID, NXlink *pSecondID)
NXstatus NXinitattrdir (NXhandle fid)
NXstatus NXsetnumberformat (NXhandle fid, int type, char *format)
NXstatus NXinitgroupdir (NXhandle fid)
NXstatus NXinquirefile (NXhandle handle, char *filename, int filenameBufferLength)
NXstatus NXisexternalgroup (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass, char *url, int urlLen)
NXstatus NXisexternaldataset (NXhandle fid, CONSTCHAR *name, char *url, int urlLen)
NXstatus NXlinkexternal (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass, CONSTCHAR *url)
NXstatus NXlinkexternaldataset (NXhandle fid, CONSTCHAR *name, CONSTCHAR *url)
NXstatus NXopenpath (NXhandle hfil, CONSTCHAR *path)
NXstatus NXopengrouppath (NXhandle hfil, CONSTCHAR *path)
NXstatus NXIprintlink (NXhandle fid, NXlink *link)
NXstatus NXgetpath (NXhandle fid, char *path, int pathlen)
NXstatus NXputattra (NXhandle handle, CONSTCHAR *name, const void *data, const int rank, const int dim[], const int iType)
NXstatus NXgetnextattra (NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
NXstatus NXgetattra (NXhandle handle, const char *name, void *data)
NXstatus NXgetattrainfo (NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
char * NXIformatNeXusTime ()
const char * NXgetversion ()
Variables
long nx_cacheSize = 1024000
Macro Definition Documentation
#define LIBSEP ":"
Definition at line 55 of file napi.c.
#define LOCKED_CALL (__call) __call
Definition at line 143 of file napi.c.
Referenced by NXclose(), NXclosedata(), NXclosegroup(), NXcompmakedata64(), NXcompress(), NXflush(), NXgetattr(), NXgetattra(), NXgetattrainfo(), NXgetattrinfo(), NXgetdata(), NXgetdataID(), NXgetgroupID(), NXgetgroupinfo(), NXgetinfo64(), NXgetnextattr(), NXgetnextattra(), NXgetnextentry(), NXgetrawinfo(), NXgetrawinfo64(), NXgetslab64(), NXinitattrdir(), NXinitgroupdir(), NXinquirefile(), NXIprintlink(), NXisexternaldataset(), NXisexternalgroup(), NXlinkexternal(), NXlinkexternaldataset(), NXmakedata64(), NXmakegroup(), NXmakelink(), NXmakenamedlink(), NXopendata(), NXopengroup(), NXputattr(), NXputattra(), NXputdata(), NXputslab64(), NXreopen(), NXsameID(), and NXsetnumberformat().
#define NUL '\0'
Definition at line 1204 of file napi.c.
Referenced by nxitrim().
#define NXBADURL 0
Definition at line 42 of file napi.c.
Referenced by NXopendata(), and NXopengroup().
#define NXFILE 1
Definition at line 43 of file napi.c.
#define PATHSEP "/"
Definition at line 56 of file napi.c.
#define THREAD_LOCAL __thread
Definition at line 57 of file napi.c.
Function Documentation
NXstatus NXclose (NXhandle * fid)
Examples:
napi_test.c.
Definition at line 688 of file napi.c.
References fileStackDepth(), killFileStack(), LOCKED_CALL, NexusFunction::nxclose, peekFileOnStack(), NexusFunction::pNexusData, and popFileStack().
Referenced by NXclosedata(), NXclosegroup(), NXfclose(), and NXICLOSE().
NXstatus NXclosedata (NXhandle fid)
Examples:
napi_test.c.
Definition at line 973 of file napi.c.
References fileStackDepth(), LOCKED_CALL, NXclose(), NexusFunction::nxclosedata, NXgetdataID(), NXsameID(), peekIDOnStack(), NexusFunction::pNexusData, and popPath().
Referenced by NXICLOSEDATA().
NXstatus NXclosegroup (NXhandle fid)
Examples:
napi_test.c.
Definition at line 824 of file napi.c.
References fileStackDepth(), LOCKED_CALL, NXclose(), NexusFunction::nxclosegroup, NXgetgroupID(), NXsameID(), peekIDOnStack(), NexusFunction::pNexusData, and popPath().
Referenced by NXICLOSEGROUP().
NXstatus NXcompmakedata (NXhandle fid, CONSTCHAR * name, int datatype, int rank, int dimensions[], int compress_type, int chunk_size[])
Examples:
napi_test.c.
Definition at line 887 of file napi.c.
References NXcompmakedata64().
Referenced by NXfcompmakedata(), and NXICOMPMAKEDATA().
NXstatus NXcompmakedata64 (NXhandle fid, CONSTCHAR * name, int datatype, int rank, int64_t dimensions[], int compress_type, int64_t chunk_size[])
Definition at line 902 of file napi.c.
References NexusFunction::checkNameSyntax, LOCKED_CALL, NXReportError(), NexusFunction::pNexusData, and validNXName().
Referenced by NXcompmakedata().
NXstatus NXcompress (NXhandle fid, int compress_type)
Definition at line 923 of file napi.c.
References LOCKED_CALL, NexusFunction::nxcompress, and NexusFunction::pNexusData.
Referenced by NXfcompress(), and NXICOMPRESS().
NXstatus NXflush (NXhandle * pHandle)
Examples:
napi_test.c.
Definition at line 1111 of file napi.c.
References LOCKED_CALL, NexusFunction::nxflush, peekFileOnStack(), and NexusFunction::pNexusData.
Referenced by NXfflush(), and NXIFLUSH().
NXstatus NXfree (void ** data)
Examples:
napi_test.c.
Definition at line 1172 of file napi.c.
References NXReportError().
Referenced by NXIFREE().
NXstatus NXgetattr (NXhandle fid, const char * name, void * data, int * datalen, int * iType)
Examples:
napi_test.c.
Definition at line 1361 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXIGETATTR(), NXisexternaldataset(), NXisexternalgroup(), NXopendata(), NXopengroup(), and NXopensourcegroup().
NXstatus NXgetattra (NXhandle handle, const char * name, void * data)
Definition at line 1959 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetattra, and NexusFunction::pNexusData.
NXstatus NXgetattrainfo (NXhandle handle, NXname pName, int * rank, int dim[], int * iType)
Definition at line 1964 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetattrainfo, and NexusFunction::pNexusData.
NXstatus NXgetattrinfo (NXhandle fid, int * iN)
Examples:
napi_test.c.
Definition at line 1372 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetattrinfo, and NexusFunction::pNexusData.
Referenced by NXIGETATTRINFO().
NXstatus NXgetdata (NXhandle fid, void * data)
Examples:
napi_test.c.
Definition at line 1238 of file napi.c.
References LOCKED_CALL, NX_CHAR, NX_MAXRANK, NexusFunction::nxgetdata, NexusFunction::nxgetinfo64, nxitrim(), NexusFunction::pNexusData, and NexusFunction::stripFlag.
Referenced by NXIGETDATA().
NXstatus NXgetdataID (NXhandle fid, NXlink * sRes)
Examples:
napi_test.c.
Definition at line 1065 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetdataID, and NexusFunction::pNexusData.
Referenced by NXclosedata(), NXIGETDATAID(), and NXopendata().
NXstatus NXgetgroupID (NXhandle fileid, NXlink * sRes)
Examples:
napi_test.c.
Definition at line 1380 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetgroupID, and NexusFunction::pNexusData.
Referenced by NXclosegroup(), NXIGETGROUPID(), and NXopengroup().
NXstatus NXgetgroupinfo (NXhandle fid, int * iN, NXname pName, NXname pClass)
Examples:
napi_test.c.
Definition at line 1388 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXIGETGROUPINFO(), and NXUfindgroup().
NXstatus NXgetinfo (NXhandle fid, int * rank, int dimension[], int * iType)
Examples:
napi_test.c.
Definition at line 1286 of file napi.c.
References NX_MAXRANK, and NXgetinfo64().
Referenced by NXIGETINFO().
NXstatus NXgetinfo64 (NXhandle fid, int * rank, int64_t dimension[], int * iType)
Definition at line 1297 of file napi.c.
References LOCKED_CALL, NX_CHAR, NexusFunction::nxgetdata, nxitrim(), NexusFunction::pNexusData, and NexusFunction::stripFlag.
Referenced by NXgetinfo(), NXgetslab(), and NXputslab().
NXstatus NXgetnextattr (NXhandle fileid, NXname pName, int * iLength, int * iType)
Examples:
napi_test.c.
Definition at line 1351 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXIGETNEXTATTR().
NXstatus NXgetnextattra (NXhandle handle, NXname pName, int * rank, int dim[], int * iType)
Definition at line 1954 of file napi.c.
References LOCKED_CALL, NexusFunction::nxgetnextattra, and NexusFunction::pNexusData.
NXstatus NXgetnextentry (NXhandle fid, NXname name, NXname nxclass, int * datatype)
Examples:
napi_test.c.
Definition at line 1189 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXIGETNEXTENTRY().
NXstatus NXgetpath (NXhandle fid, char * path, int pathlen)
Examples:
napi_test.c.
Definition at line 1936 of file napi.c.
References buildPath().
Referenced by NXfgetpath().
NXstatus NXgetrawinfo (NXhandle fid, int * rank, int dimension[], int * iType)
Definition at line 1270 of file napi.c.
References LOCKED_CALL, NX_MAXRANK, and NexusFunction::pNexusData.
Referenced by NXIGETRAWINFO().
NXstatus NXgetrawinfo64 (NXhandle fid, int * rank, int64_t dimension[], int * iType)
Definition at line 1261 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
NXstatus NXgetslab (NXhandle fid, void * data, const int iStart[], const int iSize[])
Examples:
napi_test.c.
Definition at line 1326 of file napi.c.
References NX_MAXRANK, NXgetinfo64(), and NXgetslab64().
Referenced by NXIGETSLAB().
NXstatus NXgetslab64 (NXhandle fid, void * data, const int64_t iStart[], const int64_t iSize[])
Definition at line 1341 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXgetslab().
const char* NXgetversion ()
Definition at line 2031 of file napi.c.
char* NXIformatNeXusTime ()
Definition at line 1973 of file napi.c.
References NXReportError().
NXstatus NXinitattrdir (NXhandle fid)
Definition at line 1407 of file napi.c.
References LOCKED_CALL, NexusFunction::nxinitattrdir, and NexusFunction::pNexusData.
Referenced by NXIINITATTRDIR().
NXstatus NXinitgroupdir (NXhandle fid)
Definition at line 1433 of file napi.c.
References LOCKED_CALL, NexusFunction::nxinitgroupdir, and NexusFunction::pNexusData.
Referenced by NXIINITGROUPDIR().
NXstatus NXinquirefile (NXhandle handle, char * filename, int filenameBufferLength)
Examples:
napi_test.c.
Definition at line 1440 of file napi.c.
References LOCKED_CALL, NexusFunction::nxnativeinquirefile, peekFilenameOnStack(), and NexusFunction::pNexusData.
Referenced by NXIINQUIREFILE().
NXstatus NXIprintlink (NXhandle fid, NXlink * link)
Examples:
napi_test.c.
Definition at line 1929 of file napi.c.
References LOCKED_CALL, NexusFunction::nxprintlink, and NexusFunction::pNexusData.
void NXIReportError (void * pData, char * string)
Definition at line 298 of file napi.c.
References NXReportError().
NXstatus NXisexternaldataset (NXhandle fid, CONSTCHAR * name, char * url, int urlLen)
Examples:
napi_test.c.
Definition at line 1520 of file napi.c.
References LOCKED_CALL, NX_CHAR, NexusFunction::nxclosedata, NXgetattr(), NXMDisableErrorReporting(), NXMEnableErrorReporting(), NexusFunction::nxnativeisexternallink, NexusFunction::nxopendata, and NexusFunction::pNexusData.
NXstatus NXisexternalgroup (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass, char * url, int urlLen)
Examples:
napi_test.c.
Definition at line 1478 of file napi.c.
References LOCKED_CALL, NX_CHAR, NexusFunction::nxclosegroup, NXgetattr(), NXMDisableErrorReporting(), NXMEnableErrorReporting(), NexusFunction::nxnativeisexternallink, NexusFunction::nxopengroup, and NexusFunction::pNexusData.
Referenced by NXIISEXTERNALGROUP().
char* nxitrim (char * str)
Definition at line 1206 of file napi.c.
References NUL.
Referenced by NXgetdata(), and NXgetinfo64().
NXstatus NXlinkexternal (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass, CONSTCHAR * url)
Examples:
napi_test.c.
Definition at line 1561 of file napi.c.
References LOCKED_CALL, NX_CHAR, NexusFunction::nxclosegroup, NexusFunction::nxmakegroup, NXMDisableErrorReporting(), NXMEnableErrorReporting(), NexusFunction::nxnativeexternallink, NexusFunction::nxopengroup, NXputattr(), and NexusFunction::pNexusData.
Referenced by NXILINKEXTERNAL().
NXstatus NXlinkexternaldataset (NXhandle fid, CONSTCHAR * name, CONSTCHAR * url)
Examples:
napi_test.c.
Definition at line 1609 of file napi.c.
References LOCKED_CALL, NX_CHAR, NexusFunction::nxclosedata, NexusFunction::nxnativeexternallink, NexusFunction::nxopendata, NXputattr(), and NexusFunction::pNexusData.
NXstatus NXmakedata (NXhandle fid, CONSTCHAR * name, int datatype, int rank, int dimensions[])
Examples:
napi_test.c.
Definition at line 858 of file napi.c.
References NXmakedata64().
Referenced by NXfmakedata(), and NXIMAKEDATA().
NXstatus NXmakedata64 (NXhandle fid, CONSTCHAR * name, int datatype, int rank, int64_t dimensions[])
Definition at line 868 of file napi.c.
References NexusFunction::checkNameSyntax, LOCKED_CALL, NXReportError(), NexusFunction::pNexusData, and validNXName().
Referenced by NXmakedata().
NXstatus NXmakegroup (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass)
Examples:
napi_test.c.
Definition at line 718 of file napi.c.
References NexusFunction::checkNameSyntax, LOCKED_CALL, NXReportError(), NexusFunction::pNexusData, and validNXName().
Referenced by NXIMAKEGROUP(), and NXUwritegroup().
NXstatus NXmakelink (NXhandle fid, NXlink * sLink)
Examples:
napi_test.c.
Definition at line 1073 of file napi.c.
References LOCKED_CALL, NexusFunction::nxmakelink, and NexusFunction::pNexusData.
Referenced by NXIMAKELINK().
NXstatus NXmakenamedlink (NXhandle fid, CONSTCHAR * newname, NXlink * sLink)
Examples:
napi_test.c.
Definition at line 1081 of file napi.c.
References NexusFunction::checkNameSyntax, LOCKED_CALL, NXReportError(), NexusFunction::pNexusData, and validNXName().
Referenced by NXIMAKENAMEDLINK().
NXstatus NXmalloc (void ** data, int rank, const int dimensions[], int datatype)
Examples:
napi_test.c.
Definition at line 1128 of file napi.c.
References NXmalloc64().
Referenced by NXIMALLOC().
NXstatus NXmalloc64 (void ** data, int rank, const int64_t dimensions[], int datatype)
Definition at line 1137 of file napi.c.
References NX_CHAR, NX_FLOAT32, NX_FLOAT64, NX_INT16, NX_INT32, NX_INT64, NX_INT8, NX_UINT16, NX_UINT32, NX_UINT64, NX_UINT8, and NXReportError().
Referenced by NXmalloc().
void NXMDisableErrorReporting ()
Definition at line 360 of file napi.c.
Referenced by NXisexternaldataset(), NXisexternalgroup(), NXlinkexternal(), NXopendata(), and NXopengroup().
void NXMEnableErrorReporting ()
Definition at line 375 of file napi.c.
Referenced by NXisexternaldataset(), NXisexternalgroup(), NXlinkexternal(), NXopendata(), and NXopengroup().
ErrFunc NXMGetError ()
Definition at line 337 of file napi.c.
void NXMSetError (void * pData, void(*)(void *pD, char *text) NewError)
Definition at line 319 of file napi.c.
Referenced by NXMSetTError().
void NXMSetTError (void * pData, void(*)(void *pD, char *text) NewError)
Definition at line 326 of file napi.c.
References NXMSetError().
NXstatus NXopen (CONSTCHAR * userfilename, NXaccess am, NXhandle * gHandle)
Examples:
napi_test.c.
Definition at line 463 of file napi.c.
References makeFileStack(), and NXReportError().
Referenced by NXfopen(), and NXIOPEN().
NXstatus NXopendata (NXhandle fid, CONSTCHAR * name)
Examples:
napi_test.c.
Definition at line 931 of file napi.c.
References LOCKED_CALL, NX_CHAR, NXBADURL, NXgetattr(), NXgetdataID(), NXMDisableErrorReporting(), NXMEnableErrorReporting(), NexusFunction::nxopendata, NXopenpath(), NexusFunction::pNexusData, pushPath(), and setCloseID().
Referenced by NXIOPENDATA().
NXstatus NXopengroup (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass)
Examples:
napi_test.c.
Definition at line 782 of file napi.c.
References LOCKED_CALL, NX_CHAR, NXBADURL, NXgetattr(), NXgetgroupID(), NXMDisableErrorReporting(), NXMEnableErrorReporting(), NexusFunction::nxopengroup, NXopenpath(), NexusFunction::pNexusData, pushPath(), and setCloseID().
Referenced by NXIOPENGROUP(), and NXUwritegroup().
NXstatus NXopengrouppath (NXhandle hfil, CONSTCHAR * path)
Examples:
napi_test.c.
Definition at line 1894 of file napi.c.
References NXReportError().
Referenced by NXIOPENGROUPPATH(), and NXopensourcegroup().
NXstatus NXopenpath (NXhandle hfil, CONSTCHAR * path)
Examples:
napi_test.c.
Definition at line 1861 of file napi.c.
References NXReportError().
Referenced by NXIOPENPATH(), NXopendata(), and NXopengroup().
NXstatus NXopensourcegroup (NXhandle fid)
Definition at line 1096 of file napi.c.
References NX_CHAR, NXgetattr(), NXopengrouppath(), and NXReportError().
Referenced by NXIOPENSOURCEGROUP().
NXstatus NXputattr (NXhandle fid, CONSTCHAR * name, const void * data, int datalen, int iType)
Examples:
napi_test.c.
Definition at line 1016 of file napi.c.
References NexusFunction::checkNameSyntax, LOCKED_CALL, NX_CHAR, NXReportError(), NexusFunction::pNexusData, and validNXName().
Referenced by NXfputattr(), NXIPUTATTR(), NXlinkexternal(), and NXlinkexternaldataset().
NXstatus NXputattra (NXhandle handle, CONSTCHAR * name, const void * data, const int rank, const int dim[], const int iType)
Definition at line 1949 of file napi.c.
References LOCKED_CALL, NexusFunction::nxputattra, and NexusFunction::pNexusData.
NXstatus NXputdata (NXhandle fid, const void * data)
Examples:
napi_test.c.
Definition at line 1008 of file napi.c.
References LOCKED_CALL, NexusFunction::nxputdata, and NexusFunction::pNexusData.
Referenced by NXIPUTDATA().
NXstatus NXputslab (NXhandle fid, const void * data, const int iStart[], const int iSize[])
Examples:
napi_test.c.
Definition at line 1040 of file napi.c.
References NX_MAXRANK, NXgetinfo64(), and NXputslab64().
Referenced by NXIPUTSLAB().
NXstatus NXputslab64 (NXhandle fid, const void * data, const int64_t iStart[], const int64_t iSize[])
Definition at line 1055 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXputslab().
NXstatus NXreopen (NXhandle pOrigHandle, NXhandle * pNewHandle)
Examples:
napi_test.c.
Definition at line 651 of file napi.c.
References fileStackDepth(), LOCKED_CALL, makeFileStack(), NexusFunction::nxreopen, NXReportError(), peekFilenameOnStack(), peekFileOnStack(), NexusFunction::pNexusData, and pushFileStack().
void NXReportError (char * string)
Definition at line 305 of file napi.c.
Referenced by NXcompmakedata64(), NXfcompmakedata(), NXfmakedata(), NXfree(), NXIformatNeXusTime(), NXIReportError(), NXmakedata64(), NXmakegroup(), NXmakenamedlink(), NXmalloc64(), NXopen(), NXopengrouppath(), NXopenpath(), NXopensourcegroup(), NXputattr(), NXreopen(), and NXUsetcompress().
NXstatus NXsameID (NXhandle fileid, NXlink * pFirstID, NXlink * pSecondID)
Examples:
napi_test.c.
Definition at line 1398 of file napi.c.
References LOCKED_CALL, and NexusFunction::pNexusData.
Referenced by NXclosedata(), NXclosegroup(), and NXISAMEID().
NXstatus NXsetcache (long newVal)
Definition at line 250 of file napi.c.
Referenced by NXISETCACHE().
NXstatus NXsetnumberformat (NXhandle fid, int type, char * format)
Examples:
napi_test.c.
Definition at line 1415 of file napi.c.
References LOCKED_CALL, NexusFunction::nxsetnumberformat, and NexusFunction::pNexusData.
Referenced by NXISETNUMBERFORMAT().
int validNXName (const char * name, int allow_colon)
valid NeXus names
Definition at line 151 of file napi.c.
Referenced by NXcompmakedata64(), NXmakedata64(), NXmakegroup(), NXmakenamedlink(), and NXputattr().
Variable Documentation
long nx_cacheSize = 1024000
Definition at line 248 of file napi.c.