NeXus: /isis/nexus_temp/src/napiu.c File Reference
napiu.c File Reference
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <time.h>
#include "napiu.h"
#include "napi_internal.h"
Macros
#define DO_GLOBAL(__name)
Functions
NXstatus NXUwriteglobals (NXhandle file_id, const char *user, const char *affiliation, const char *address, const char *telephone_number, const char *fax_number, const char *email)
NXstatus NXUwritegroup (NXhandle file_id, const char *group_name, const char *group_class)
NXstatus NXUwritedata (NXhandle file_id, const char *data_name, const void *data, int data_type, int rank, const int dim[], const char *units, const int start[], const int size[])
NXstatus NXUreaddata (NXhandle file_id, const char *data_name, void *data, char *units, const int start[], const int size[])
NXstatus NXUwritehistogram (NXhandle file_id, const char *data_name, const void *data, const char *units)
NXstatus NXUreadhistogram (NXhandle file_id, const char *data_name, void *data, char *units)
NXstatus NXUsetcompress (NXhandle file_id, int comp_type, int comp_size)
NXstatus NXUfindgroup (NXhandle file_id, const char *group_name, char *group_class)
NXstatus NXUfindclass (NXhandle file_id, const char *group_class, char *group_name, int find_index)
NXstatus NXUfinddata (NXhandle file_id, const char *data_name)
NXstatus NXUfindattr (NXhandle file_id, const char *attr_name)
NXstatus NXUfindsignal (NXhandle file_id, int signal, char *data_name, int *data_rank, int *data_type, int data_dimensions[])
NXstatus NXUfindaxis (NXhandle file_id, int axis, int primary, char *data_name, int *data_rank, int *data_type, int data_dimensions[])
NXstatus NXUfindlink (NXhandle file_id, NXlink *group_id, const char *group_class)
NXstatus NXUresumelink (NXhandle file_id, NXlink group_id)
Macro Definition Documentation
#define DO_GLOBAL (__name)
Value:
if (__name != NULL) \
        { \
                if (NXputattr(file_id, #__name, (char*)__name, (int)strlen(__name), NX_CHAR) != NX_OK) \
                { \
                        return NX_ERROR; \
                } \
        }
Definition at line 35 of file napiu.c.
Referenced by NXUwriteglobals().
Function Documentation
NXstatus NXUfindattr (NXhandle file_id, const char * attr_name)
Definition at line 136 of file napiu.c.
NXstatus NXUfindaxis (NXhandle file_id, int axis, int primary, char * data_name, int * data_rank, int * data_type, int data_dimensions[])
Definition at line 146 of file napiu.c.
NXstatus NXUfindclass (NXhandle file_id, const char * group_class, char * group_name, int find_index)
Definition at line 125 of file napiu.c.
NXstatus NXUfinddata (NXhandle file_id, const char * data_name)
Definition at line 131 of file napiu.c.
NXstatus NXUfindgroup (NXhandle file_id, const char * group_name, char * group_class)
Definition at line 113 of file napiu.c.
References NXgetgroupinfo().
NXstatus NXUfindlink (NXhandle file_id, NXlink * group_id, const char * group_class)
Definition at line 151 of file napiu.c.
NXstatus NXUfindsignal (NXhandle file_id, int signal, char * data_name, int * data_rank, int * data_type, int data_dimensions[])
Definition at line 141 of file napiu.c.
NXstatus NXUreaddata (NXhandle file_id, const char * data_name, void * data, char * units, const int start[], const int size[])
Definition at line 72 of file napiu.c.
NXstatus NXUreadhistogram (NXhandle file_id, const char * data_name, void * data, char * units)
Definition at line 82 of file napiu.c.
NXstatus NXUresumelink (NXhandle file_id, NXlink group_id)
Definition at line 156 of file napiu.c.
NXstatus NXUsetcompress (NXhandle file_id, int comp_type, int comp_size)
Definition at line 91 of file napiu.c.
References NXReportError().
NXstatus NXUwritedata (NXhandle file_id, const char * data_name, const void * data, int data_type, int rank, const int dim[], const char * units, const int start[], const int size[])
Definition at line 67 of file napiu.c.
NXstatus NXUwriteglobals (NXhandle file_id, const char * user, const char * affiliation, const char * address, const char * telephone_number, const char * fax_number, const char * email)
Definition at line 44 of file napiu.c.
References DO_GLOBAL.
NXstatus NXUwritegroup (NXhandle file_id, const char * group_name, const char * group_class)
Definition at line 56 of file napiu.c.
References NXmakegroup(), and NXopengroup().
NXstatus NXUwritehistogram (NXhandle file_id, const char * data_name, const void * data, const char * units)
Definition at line 77 of file napiu.c.