NeXus: /isis/nexus_temp/src/napi_exports.h File Reference
napi_exports.h File Reference
Functions
NXstatus CALL_MODE NXISETCACHE (long newVal)
NXstatus CALL_MODE NXIOPEN (CONSTCHAR *filename, NXaccess am, NXhandle *gHandle)
NXstatus CALL_MODE NXICLOSE (NXhandle *fid)
NXstatus CALL_MODE NXIFLUSH (NXhandle *pHandle)
NXstatus CALL_MODE NXIMAKEGROUP (NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
NXstatus CALL_MODE NXIOPENGROUP (NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
NXstatus CALL_MODE NXIOPENPATH (NXhandle handle, CONSTCHAR *path)
NXstatus CALL_MODE NXIOPENGROUPPATH (NXhandle handle, CONSTCHAR *path)
NXstatus CALL_MODE NXICLOSEGROUP (NXhandle handle)
NXstatus CALL_MODE NXIMAKEDATA (NXhandle handle, CONSTCHAR *label, int datatype, int rank, int dim[])
NXstatus CALL_MODE NXICOMPMAKEDATA (NXhandle handle, CONSTCHAR *label, int datatype, int rank, int dim[], int comp_typ, int bufsize[])
NXstatus CALL_MODE NXICOMPRESS (NXhandle handle, int compr_type)
NXstatus CALL_MODE NXIOPENDATA (NXhandle handle, CONSTCHAR *label)
NXstatus CALL_MODE NXICLOSEDATA (NXhandle handle)
NXstatus CALL_MODE NXIPUTDATA (NXhandle handle, void *data)
NXstatus CALL_MODE NXIPUTATTR (NXhandle handle, CONSTCHAR *name, void *data, int iDataLen, int iType)
NXstatus CALL_MODE NXIPUTSLAB (NXhandle handle, void *data, int start[], int size[])
NXstatus CALL_MODE NXIGETDATAID (NXhandle handle, NXlink *pLink)
NXstatus CALL_MODE NXIMAKELINK (NXhandle handle, NXlink *pLink)
NXstatus CALL_MODE NXIOPENSOURCEGROUP (NXhandle handle)
NXstatus CALL_MODE NXIGETDATA (NXhandle handle, void *data)
NXstatus CALL_MODE NXIGETINFO (NXhandle handle, int *rank, int dimension[], int *datatype)
NXstatus CALL_MODE NXIGETNEXTENTRY (NXhandle handle, NXname name, NXname nxclass, int *datatype)
NXstatus CALL_MODE NXIGETSLAB (NXhandle handle, void *data, int start[], int size[])
NXstatus CALL_MODE NXIGETNEXTATTR (NXhandle handle, NXname pName, int *iLength, int *iType)
NXstatus CALL_MODE NXIGETATTR (NXhandle handle, char *name, void *data, int *iDataLen, int *iType)
NXstatus CALL_MODE NXIGETATTRINFO (NXhandle handle, int *no_items)
NXstatus CALL_MODE NXIGETGROUPID (NXhandle handle, NXlink *pLink)
NXstatus CALL_MODE NXIGETGROUPINFO (NXhandle handle, int *no_items, NXname name, NXname nxclass)
NXstatus CALL_MODE NXISAMEID (NXhandle handle, NXlink *pFirstID, NXlink *pSecondID)
NXstatus CALL_MODE NXIINITGROUPDIR (NXhandle handle)
NXstatus CALL_MODE NXIINITATTRDIR (NXhandle handle)
NXstatus CALL_MODE NXISETNUMBERFORMAT (NXhandle handle, int type, char *format)
NXstatus CALL_MODE NXIMALLOC (void **data, int rank, int dimensions[], int datatype)
NXstatus CALL_MODE NXIFREE (void **data)
NXstatus CALL_MODE NXIFOPEN (char *filename, NXaccess *am, NexusFunction *pHandle)
NXstatus CALL_MODE NXIFCLOSE (NexusFunction *pHandle)
NXstatus CALL_MODE NXIFPUTATTR (NXhandle fid, char *name, void *data, int *pDatalen, int *pIType)
NXstatus CALL_MODE NXIFCOMPRESS (NXhandle fid, int *compr_type)
NXstatus CALL_MODE NXIFCOMPMAKEDATA (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[], int *compression_type, int chunk[])
NXstatus CALL_MODE NXIFMAKEDATA (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[])
NXstatus CALL_MODE NXIFFLUSH (NexusFunction *pHandle)
NXstatus CALL_MODE NXIINQUIREFILE (NXhandle handle, char *filename, int filenameBufferLength)
NXstatus CALL_MODE NXIISEXTERNALGROUP (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass, char *url, int urlLen)
NXstatus CALL_MODE NXILINKEXTERNAL (NXhandle fid, CONSTCHAR *name, CONSTCHAR *nxclass, CONSTCHAR *url)
NXstatus CALL_MODE NXIMAKENAMEDLINK (NXhandle fid, CONSTCHAR *newname, NXlink *pLink)
NXstatus CALL_MODE NXIGETRAWINFO (NXhandle handle, int *rank, int dimension[], int *datatype)
Function Documentation
NXstatus CALL_MODE NXICLOSE (NXhandle * fid)
Definition at line 22 of file napi_exports.h.
References NXclose().
NXstatus CALL_MODE NXICLOSEDATA (NXhandle handle)
Definition at line 77 of file napi_exports.h.
References NXclosedata().
NXstatus CALL_MODE NXICLOSEGROUP (NXhandle handle)
Definition at line 52 of file napi_exports.h.
References NXclosegroup().
NXstatus CALL_MODE NXICOMPMAKEDATA (NXhandle handle, CONSTCHAR * label, int datatype, int rank, int dim[], int comp_typ, int bufsize[])
Definition at line 62 of file napi_exports.h.
References NXcompmakedata().
NXstatus CALL_MODE NXICOMPRESS (NXhandle handle, int compr_type)
Definition at line 67 of file napi_exports.h.
References NXcompress().
NXstatus CALL_MODE NXIFCLOSE (NexusFunction * pHandle)
Definition at line 203 of file napi_exports.h.
References NXfclose.
NXstatus CALL_MODE NXIFCOMPMAKEDATA (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[], int * compression_type, int chunk[])
Definition at line 219 of file napi_exports.h.
References NXfcompmakedata.
NXstatus CALL_MODE NXIFCOMPRESS (NXhandle fid, int * compr_type)
Definition at line 214 of file napi_exports.h.
References NXfcompress.
NXstatus CALL_MODE NXIFFLUSH (NexusFunction * pHandle)
Definition at line 234 of file napi_exports.h.
References NXfflush.
NXstatus CALL_MODE NXIFLUSH (NXhandle * pHandle)
Definition at line 27 of file napi_exports.h.
References NXflush().
NXstatus CALL_MODE NXIFMAKEDATA (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[])
Definition at line 228 of file napi_exports.h.
References NXfmakedata.
NXstatus CALL_MODE NXIFOPEN (char * filename, NXaccess * am, NexusFunction * pHandle)
Definition at line 197 of file napi_exports.h.
References NXfopen.
NXstatus CALL_MODE NXIFPUTATTR (NXhandle fid, char * name, void * data, int * pDatalen, int * pIType)
Definition at line 208 of file napi_exports.h.
References NXfputattr.
NXstatus CALL_MODE NXIFREE (void ** data)
Definition at line 180 of file napi_exports.h.
References NXfree().
NXstatus CALL_MODE NXIGETATTR (NXhandle handle, char * name, void * data, int * iDataLen, int * iType)
Definition at line 137 of file napi_exports.h.
References NXgetattr().
NXstatus CALL_MODE NXIGETATTRINFO (NXhandle handle, int * no_items)
Definition at line 142 of file napi_exports.h.
References NXgetattrinfo().
NXstatus CALL_MODE NXIGETDATA (NXhandle handle, void * data)
Definition at line 112 of file napi_exports.h.
References NXgetdata().
NXstatus CALL_MODE NXIGETDATAID (NXhandle handle, NXlink * pLink)
Definition at line 97 of file napi_exports.h.
References NXgetdataID().
NXstatus CALL_MODE NXIGETGROUPID (NXhandle handle, NXlink * pLink)
Definition at line 147 of file napi_exports.h.
References NXgetgroupID().
NXstatus CALL_MODE NXIGETGROUPINFO (NXhandle handle, int * no_items, NXname name, NXname nxclass)
Definition at line 152 of file napi_exports.h.
References NXgetgroupinfo().
NXstatus CALL_MODE NXIGETINFO (NXhandle handle, int * rank, int dimension[], int * datatype)
Definition at line 117 of file napi_exports.h.
References NXgetinfo().
NXstatus CALL_MODE NXIGETNEXTATTR (NXhandle handle, NXname pName, int * iLength, int * iType)
Definition at line 132 of file napi_exports.h.
References NXgetnextattr().
NXstatus CALL_MODE NXIGETNEXTENTRY (NXhandle handle, NXname name, NXname nxclass, int * datatype)
Definition at line 122 of file napi_exports.h.
References NXgetnextentry().
NXstatus CALL_MODE NXIGETRAWINFO (NXhandle handle, int * rank, int dimension[], int * datatype)
Definition at line 259 of file napi_exports.h.
References NXgetrawinfo().
NXstatus CALL_MODE NXIGETSLAB (NXhandle handle, void * data, int start[], int size[])
Definition at line 127 of file napi_exports.h.
References NXgetslab().
NXstatus CALL_MODE NXIINITATTRDIR (NXhandle handle)
Definition at line 166 of file napi_exports.h.
References NXinitattrdir().
NXstatus CALL_MODE NXIINITGROUPDIR (NXhandle handle)
Definition at line 162 of file napi_exports.h.
References NXinitgroupdir().
NXstatus CALL_MODE NXIINQUIREFILE (NXhandle handle, char * filename, int filenameBufferLength)
Definition at line 239 of file napi_exports.h.
References NXinquirefile().
NXstatus CALL_MODE NXIISEXTERNALGROUP (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass, char * url, int urlLen)
Definition at line 244 of file napi_exports.h.
References NXisexternalgroup().
NXstatus CALL_MODE NXILINKEXTERNAL (NXhandle fid, CONSTCHAR * name, CONSTCHAR * nxclass, CONSTCHAR * url)
Definition at line 249 of file napi_exports.h.
References NXlinkexternal().
NXstatus CALL_MODE NXIMAKEDATA (NXhandle handle, CONSTCHAR * label, int datatype, int rank, int dim[])
Definition at line 57 of file napi_exports.h.
References NXmakedata().
NXstatus CALL_MODE NXIMAKEGROUP (NXhandle handle, CONSTCHAR * name, CONSTCHAR * NXclass)
Definition at line 32 of file napi_exports.h.
References NXmakegroup().
NXstatus CALL_MODE NXIMAKELINK (NXhandle handle, NXlink * pLink)
Definition at line 102 of file napi_exports.h.
References NXmakelink().
NXstatus CALL_MODE NXIMAKENAMEDLINK (NXhandle fid, CONSTCHAR * newname, NXlink * pLink)
Definition at line 254 of file napi_exports.h.
References NXmakenamedlink().
NXstatus CALL_MODE NXIMALLOC (void ** data, int rank, int dimensions[], int datatype)
Definition at line 175 of file napi_exports.h.
References NXmalloc().
NXstatus CALL_MODE NXIOPEN (CONSTCHAR * filename, NXaccess am, NXhandle * gHandle)
Definition at line 17 of file napi_exports.h.
References NXopen().
NXstatus CALL_MODE NXIOPENDATA (NXhandle handle, CONSTCHAR * label)
Definition at line 72 of file napi_exports.h.
References NXopendata().
NXstatus CALL_MODE NXIOPENGROUP (NXhandle handle, CONSTCHAR * name, CONSTCHAR * NXclass)
Definition at line 37 of file napi_exports.h.
References NXopengroup().
NXstatus CALL_MODE NXIOPENGROUPPATH (NXhandle handle, CONSTCHAR * path)
Definition at line 47 of file napi_exports.h.
References NXopengrouppath().
NXstatus CALL_MODE NXIOPENPATH (NXhandle handle, CONSTCHAR * path)
Definition at line 42 of file napi_exports.h.
References NXopenpath().
NXstatus CALL_MODE NXIOPENSOURCEGROUP (NXhandle handle)
Definition at line 107 of file napi_exports.h.
References NXopensourcegroup().
NXstatus CALL_MODE NXIPUTATTR (NXhandle handle, CONSTCHAR * name, void * data, int iDataLen, int iType)
Definition at line 87 of file napi_exports.h.
References NXputattr().
NXstatus CALL_MODE NXIPUTDATA (NXhandle handle, void * data)
Definition at line 82 of file napi_exports.h.
References NXputdata().
NXstatus CALL_MODE NXIPUTSLAB (NXhandle handle, void * data, int start[], int size[])
Definition at line 92 of file napi_exports.h.
References NXputslab().
NXstatus CALL_MODE NXISAMEID (NXhandle handle, NXlink * pFirstID, NXlink * pSecondID)
Definition at line 157 of file napi_exports.h.
References NXsameID().
NXstatus CALL_MODE NXISETCACHE (long newVal)
Definition at line 5 of file napi_exports.h.
References NXsetcache().
NXstatus CALL_MODE NXISETNUMBERFORMAT (NXhandle handle, int type, char * format)
Definition at line 170 of file napi_exports.h.
References NXsetnumberformat().