NeXus: /isis/nexus_temp/src/napi_fortran_helper.c File Reference
napi_fortran_helper.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <napi_fortran_helper.h>
#include <napi_internal.h>
#include "nxstack.h"
Functions
NXstatus NXfopen (char *filename, NXaccess *am, NXhandle pHandle)
NXstatus NXfclose (NXhandle pHandle)
NXstatus NXfflush (NXhandle pHandle)
NXstatus NXfmakedata (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[])
NXstatus NXfcompmakedata (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[], int *compression_type, int chunk[])
NXstatus NXfcompress (NXhandle fid, int *compr_type)
NXstatus NXfputattr (NXhandle fid, const char *name, const void *data, int *pDatalen, int *pIType)
int nxisnprintf (char *buffer, int len, const char *format,...)
NXstatus NXfgetpath (NXhandle fid, char *path, int *pathlen)
Function Documentation
NXstatus NXfclose (NXhandle pHandle)
Definition at line 65 of file napi_fortran_helper.c.
References getFileStackSize(), and NXclose().
NXstatus NXfcompmakedata (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[], int * compression_type, int chunk[])
Definition at line 115 of file napi_fortran_helper.c.
References NXcompmakedata(), and NXReportError().
NXstatus NXfcompress (NXhandle fid, int * compr_type)
Definition at line 148 of file napi_fortran_helper.c.
References NXcompress().
NXstatus NXfflush (NXhandle pHandle)
Definition at line 77 of file napi_fortran_helper.c.
References getFileStackSize(), and NXflush().
NXstatus NXfgetpath (NXhandle fid, char * path, int * pathlen)
Definition at line 174 of file napi_fortran_helper.c.
References NXgetpath().
NXstatus NXfmakedata (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[])
Definition at line 89 of file napi_fortran_helper.c.
References NXmakedata(), and NXReportError().
NXstatus NXfopen (char * filename, NXaccess * am, NXhandle pHandle)
Definition at line 44 of file napi_fortran_helper.c.
References getFileStackSize(), and NXopen().
NXstatus NXfputattr (NXhandle fid, const char * name, const void * data, int * pDatalen, int * pIType)
Definition at line 154 of file napi_fortran_helper.c.
References NXputattr().
int nxisnprintf (char * buffer, int len, const char * format, ...)
Definition at line 163 of file napi_fortran_helper.c.