NeXus: /isis/nexus_temp/include/napi_fortran_helper.h File Reference
napi_fortran_helper.h File Reference
#include <napi.h>
Macros
#define NXfopen MANGLE(nxifopen)
#define NXfclose MANGLE(nxifclose)
#define NXfflush MANGLE(nxifflush)
#define NXfmakedata MANGLE(nxifmakedata)
#define NXfcompmakedata MANGLE(nxifcompmakedata)
#define NXfcompress MANGLE(nxifcompress)
#define NXfputattr MANGLE(nxifputattr)
#define NXfgetpath MANGLE(nxifgetpath)
Functions
NXstatus NXfopen (char *filename, NXaccess *am, NXhandle pHandle)
NXstatus NXfclose (NXhandle pHandle)
NXstatus NXfputattr (NXhandle fid, const char *name, const void *data, int *pDatalen, int *pIType)
NXstatus NXfcompress (NXhandle fid, int *compr_type)
NXstatus NXfcompmakedata (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[], int *compression_type, int chunk[])
NXstatus NXfmakedata (NXhandle fid, char *name, int *pDatatype, int *pRank, int dimensions[])
NXstatus NXfflush (NXhandle pHandle)
NXstatus NXfgetpath (NXhandle fid, char *path, int *pathlen)
Macro Definition Documentation
#define NXfclose MANGLE(nxifclose)
Definition at line 33 of file napi_fortran_helper.h.
Referenced by NXIFCLOSE().
#define NXfcompmakedata MANGLE(nxifcompmakedata)
Definition at line 36 of file napi_fortran_helper.h.
Referenced by NXIFCOMPMAKEDATA().
#define NXfcompress MANGLE(nxifcompress)
Definition at line 37 of file napi_fortran_helper.h.
Referenced by NXIFCOMPRESS().
#define NXfflush MANGLE(nxifflush)
Definition at line 34 of file napi_fortran_helper.h.
Referenced by NXIFFLUSH().
#define NXfgetpath MANGLE(nxifgetpath)
Definition at line 39 of file napi_fortran_helper.h.
#define NXfmakedata MANGLE(nxifmakedata)
Definition at line 35 of file napi_fortran_helper.h.
Referenced by NXIFMAKEDATA().
#define NXfopen MANGLE(nxifopen)
Definition at line 32 of file napi_fortran_helper.h.
Referenced by NXIFOPEN().
#define NXfputattr MANGLE(nxifputattr)
Definition at line 38 of file napi_fortran_helper.h.
Referenced by NXIFPUTATTR().
Function Documentation
NXstatus NXfclose (NXhandle pHandle)
Definition at line 65 of file napi_fortran_helper.c.
References getFileStackSize(), and NXclose().
NXstatus NXfcompmakedata (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[], int * compression_type, int chunk[])
Definition at line 115 of file napi_fortran_helper.c.
References NXcompmakedata(), and NXReportError().
NXstatus NXfcompress (NXhandle fid, int * compr_type)
Definition at line 148 of file napi_fortran_helper.c.
References NXcompress().
NXstatus NXfflush (NXhandle pHandle)
Definition at line 77 of file napi_fortran_helper.c.
References getFileStackSize(), and NXflush().
NXstatus NXfgetpath (NXhandle fid, char * path, int * pathlen)
Definition at line 174 of file napi_fortran_helper.c.
References NXgetpath().
NXstatus NXfmakedata (NXhandle fid, char * name, int * pDatatype, int * pRank, int dimensions[])
Definition at line 89 of file napi_fortran_helper.c.
References NXmakedata(), and NXReportError().
NXstatus NXfopen (char * filename, NXaccess * am, NXhandle pHandle)
Definition at line 44 of file napi_fortran_helper.c.
References getFileStackSize(), and NXopen().
NXstatus NXfputattr (NXhandle fid, const char * name, const void * data, int * pDatalen, int * pIType)
Definition at line 154 of file napi_fortran_helper.c.
References NXputattr().