NeXus: /isis/nexus_temp/src/nxdataset.c File Reference
nxdataset.c File Reference
#include <stdlib.h>
#include <string.h>
#include "nxdataset.h"
Functions
pNXDS createNXDataset (int rank, int typecode, int64_t dim[])
pNXDS createTextNXDataset (char *name)
void dropNXDataset (pNXDS dataset)
int getNXDatasetRank (pNXDS dataset)
int getNXDatasetDim (pNXDS dataset, int which)
int getNXDatasetType (pNXDS dataset)
int getNXDatasetLength (pNXDS dataset)
int getNXDatasetByteLength (pNXDS dataset)
double getNXDatasetValue (pNXDS dataset, int64_t pos[])
double getNXDatasetValueAt (pNXDS dataset, int64_t address)
char * getNXDatasetText (pNXDS dataset)
int putNXDatasetValue (pNXDS dataset, int64_t pos[], double value)
int putNXDatasetValueAt (pNXDS dataset, int64_t address, double value)
Function Documentation
pNXDS createNXDataset (int rank, int typecode, int64_t dim[])
Definition at line 36 of file nxdataset.c.
References pNXDS::dim, pNXDS::format, MAGIC, pNXDS::magic, pNXDS::ptr, pNXDS::rank, pNXDS::type, and pNXDS::u.
pNXDS createTextNXDataset (char * name)
Definition at line 69 of file nxdataset.c.
References pNXDS::cPtr, pNXDS::dim, MAGIC, pNXDS::magic, NX_CHAR, pNXDS::ptr, pNXDS::rank, pNXDS::type, and pNXDS::u.
void dropNXDataset (pNXDS dataset)
Definition at line 89 of file nxdataset.c.
References pNXDS::dim, pNXDS::format, MAGIC, pNXDS::magic, pNXDS::ptr, and pNXDS::u.
int getNXDatasetByteLength (pNXDS dataset)
Definition at line 157 of file nxdataset.c.
References getNXDatasetLength(), and pNXDS::type.
int getNXDatasetDim (pNXDS dataset, int which)
Definition at line 118 of file nxdataset.c.
References pNXDS::dim, MAGIC, pNXDS::magic, and pNXDS::rank.
int getNXDatasetLength (pNXDS dataset)
Definition at line 141 of file nxdataset.c.
References pNXDS::dim, MAGIC, and pNXDS::magic.
Referenced by getNXDatasetByteLength().
int getNXDatasetRank (pNXDS dataset)
Definition at line 108 of file nxdataset.c.
References MAGIC, pNXDS::magic, and pNXDS::rank.
char* getNXDatasetText (pNXDS dataset)
Definition at line 230 of file nxdataset.c.
References pNXDS::cPtr, pNXDS::dim, MAGIC, pNXDS::magic, NX_FLOAT32, NX_FLOAT64, NX_INT16, NX_INT32, NX_INT64, NX_UINT16, NX_UINT32, NX_UINT64, pNXDS::rank, pNXDS::type, and pNXDS::u.
int getNXDatasetType (pNXDS dataset)
Definition at line 131 of file nxdataset.c.
References MAGIC, pNXDS::magic, and pNXDS::type.
double getNXDatasetValue (pNXDS dataset, int64_t pos[])
Definition at line 180 of file nxdataset.c.
References getNXDatasetValueAt(), MAGIC, and pNXDS::magic.
double getNXDatasetValueAt (pNXDS dataset, int64_t address)
Definition at line 194 of file nxdataset.c.
References pNXDS::cPtr, pNXDS::dPtr, pNXDS::fPtr, pNXDS::iPtr, pNXDS::lPtr, MAGIC, pNXDS::magic, NX_FLOAT32, NX_FLOAT64, NX_INT16, NX_INT32, NX_INT64, NX_UINT16, NX_UINT32, NX_UINT64, pNXDS::sPtr, pNXDS::type, and pNXDS::u.
Referenced by getNXDatasetValue().
int putNXDatasetValue (pNXDS dataset, int64_t pos[], double value)
Definition at line 267 of file nxdataset.c.
References MAGIC, pNXDS::magic, and putNXDatasetValueAt().
int putNXDatasetValueAt (pNXDS dataset, int64_t address, double value)
Definition at line 281 of file nxdataset.c.
References pNXDS::cPtr, pNXDS::dPtr, pNXDS::fPtr, pNXDS::iPtr, pNXDS::lPtr, NX_FLOAT32, NX_FLOAT64, NX_INT16, NX_INT32, NX_INT64, NX_UINT16, NX_UINT32, NX_UINT64, pNXDS::sPtr, pNXDS::type, and pNXDS::u.
Referenced by putNXDatasetValue().