NeXus: /isis/nexus_temp/src/nxstack.c File Reference
nxstack.c File Reference
#include <stdlib.h>
#include <string.h>
#include <napi.h>
#include <napi_internal.h>
#include "nxstack.h"
Data Structures
struct fileStackEntry
struct __fileStack
Typedefs
typedef struct __fileStack fileStack
Functions
pFileStack makeFileStack ()
void killFileStack (pFileStack self)
int getFileStackSize ()
void pushFileStack (pFileStack self, pNexusFunction pDriv, char *file)
void popFileStack (pFileStack self)
pNexusFunction peekFileOnStack (pFileStack self)
char * peekFilenameOnStack (pFileStack self)
void peekIDOnStack (pFileStack self, NXlink *id)
void setCloseID (pFileStack self, NXlink id)
int fileStackDepth (pFileStack self)
void pushPath (pFileStack self, const char *name)
void popPath (pFileStack self)
int buildPath (pFileStack self, char *path, int pathlen)
Typedef Documentation
typedef struct __fileStack fileStack
Function Documentation
int buildPath (pFileStack self, char * path, int pathlen)
Definition at line 125 of file nxstack.c.
Referenced by NXgetpath().
int fileStackDepth (pFileStack self)
Definition at line 109 of file nxstack.c.
Referenced by NXclose(), NXclosedata(), NXclosegroup(), and NXreopen().
int getFileStackSize ()
Definition at line 69 of file nxstack.c.
Referenced by NXfclose(), NXfflush(), and NXfopen().
void killFileStack (pFileStack self)
Definition at line 63 of file nxstack.c.
Referenced by NXclose().
pFileStack makeFileStack ()
Definition at line 50 of file nxstack.c.
References __fileStack::fileStackPointer, and __fileStack::pathPointer.
Referenced by NXopen(), and NXreopen().
char* peekFilenameOnStack (pFileStack self)
Definition at line 97 of file nxstack.c.
Referenced by NXinquirefile(), and NXreopen().
pNexusFunction peekFileOnStack (pFileStack self)
Definition at line 93 of file nxstack.c.
Referenced by NXclose(), NXflush(), and NXreopen().
void peekIDOnStack (pFileStack self, NXlink * id)
Definition at line 101 of file nxstack.c.
Referenced by NXclosedata(), and NXclosegroup().
void popFileStack (pFileStack self)
Definition at line 86 of file nxstack.c.
Referenced by NXclose().
void popPath (pFileStack self)
Definition at line 118 of file nxstack.c.
Referenced by NXclosedata(), and NXclosegroup().
void pushFileStack (pFileStack self, pNexusFunction pDriv, char * file)
Definition at line 73 of file nxstack.c.
Referenced by NXreopen().
void pushPath (pFileStack self, const char * name)
Definition at line 113 of file nxstack.c.
Referenced by NXopendata(), and NXopengroup().
void setCloseID (pFileStack self, NXlink id)
Definition at line 105 of file nxstack.c.
Referenced by NXopendata(), and NXopengroup().