NeXus: NexusFunction Struct Reference
NexusFunction Struct Reference
#include <napi_internal.h>
Data Fields
NXhandle pNexusData
NXstatus(* nxreopen)(NXhandle pOrigHandle, NXhandle *pNewHandle)
NXstatus(* nxclose)(NXhandle *pHandle)
NXstatus(* nxflush)(NXhandle *pHandle)
NXstatus(* nxmakegroup)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
NXstatus(* nxopengroup)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
NXstatus(* nxclosegroup)(NXhandle handle)
NXstatus(* nxmakedata64)(NXhandle handle, CONSTCHAR *label, int datatype, int rank, int64_t dim[])
NXstatus(* nxcompmakedata64)(NXhandle handle, CONSTCHAR *label, int datatype, int rank, int64_t dim[], int comp_typ, int64_t bufsize[])
NXstatus(* nxcompress)(NXhandle handle, int compr_type)
NXstatus(* nxopendata)(NXhandle handle, CONSTCHAR *label)
NXstatus(* nxclosedata)(NXhandle handle)
NXstatus(* nxputdata)(NXhandle handle, const void *data)
NXstatus(* nxputattr)(NXhandle handle, CONSTCHAR *name, const void *data, int iDataLen, int iType)
NXstatus(* nxputattra)(NXhandle handle, CONSTCHAR *name, const void *data, const int rank, const int dim[], const int iType)
NXstatus(* nxputslab64)(NXhandle handle, const void *data, const int64_t start[], const int64_t size[])
NXstatus(* nxgetdataID)(NXhandle handle, NXlink *pLink)
NXstatus(* nxmakelink)(NXhandle handle, NXlink *pLink)
NXstatus(* nxmakenamedlink)(NXhandle handle, CONSTCHAR *newname, NXlink *pLink)
NXstatus(* nxgetdata)(NXhandle handle, void *data)
NXstatus(* nxgetinfo64)(NXhandle handle, int *rank, int64_t dimension[], int *datatype)
NXstatus(* nxgetnextentry)(NXhandle handle, NXname name, NXname nxclass, int *datatype)
NXstatus(* nxgetslab64)(NXhandle handle, void *data, const int64_t start[], const int64_t size[])
NXstatus(* nxgetnextattr)(NXhandle handle, NXname pName, int *iLength, int *iType)
NXstatus(* nxgetnextattra)(NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
NXstatus(* nxgetattr)(NXhandle handle, const char *name, void *data, int *iDataLen, int *iType)
NXstatus(* nxgetattra)(NXhandle handle, const char *name, void *data)
NXstatus(* nxgetattrainfo)(NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
NXstatus(* nxgetattrinfo)(NXhandle handle, int *no_items)
NXstatus(* nxgetgroupID)(NXhandle handle, NXlink *pLink)
NXstatus(* nxgetgroupinfo)(NXhandle handle, int *no_items, NXname name, NXname nxclass)
NXstatus(* nxsameID)(NXhandle handle, NXlink *pFirstID, NXlink *pSecondID)
NXstatus(* nxinitgroupdir)(NXhandle handle)
NXstatus(* nxinitattrdir)(NXhandle handle)
NXstatus(* nxsetnumberformat)(NXhandle handle, int type, char *format)
NXstatus(* nxprintlink)(NXhandle handle, NXlink *link)
NXstatus(* nxnativeexternallink)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *externalfile, CONSTCHAR *remotetarget)
NXstatus(* nxnativeinquirefile)(NXhandle handle, char *externalfile, const int filenamelength)
NXstatus(* nxnativeisexternallink)(NXhandle handle, CONSTCHAR *name, char *url, int urllen)
int stripFlag
int checkNameSyntax
NXaccess access_mode
Detailed Description
Definition at line 40 of file napi_internal.h.
Field Documentation
NXaccess NexusFunction::access_mode
Definition at line 82 of file napi_internal.h.
int NexusFunction::checkNameSyntax
Definition at line 81 of file napi_internal.h.
Referenced by NXcompmakedata64(), NXmakedata64(), NXmakegroup(), NXmakenamedlink(), and NXputattr().
NXstatus(* NexusFunction::nxclose)(NXhandle *pHandle)
Definition at line 43 of file napi_internal.h.
Referenced by NXclose().
NXstatus(* NexusFunction::nxclosedata)(NXhandle handle)
Definition at line 52 of file napi_internal.h.
Referenced by NXclosedata(), NXisexternaldataset(), and NXlinkexternaldataset().
NXstatus(* NexusFunction::nxclosegroup)(NXhandle handle)
Definition at line 47 of file napi_internal.h.
Referenced by NXclosegroup(), NXisexternalgroup(), and NXlinkexternal().
NXstatus(* NexusFunction::nxcompmakedata64)(NXhandle handle, CONSTCHAR *label, int datatype, int rank, int64_t dim[], int comp_typ, int64_t bufsize[])
Definition at line 49 of file napi_internal.h.
NXstatus(* NexusFunction::nxcompress)(NXhandle handle, int compr_type)
Definition at line 50 of file napi_internal.h.
Referenced by NXcompress().
NXstatus(* NexusFunction::nxflush)(NXhandle *pHandle)
Definition at line 44 of file napi_internal.h.
Referenced by NXflush().
NXstatus(* NexusFunction::nxgetattr)(NXhandle handle, const char *name, void *data, int *iDataLen, int *iType)
Definition at line 66 of file napi_internal.h.
NXstatus(* NexusFunction::nxgetattra)(NXhandle handle, const char *name, void *data)
Definition at line 67 of file napi_internal.h.
Referenced by NXgetattra().
NXstatus(* NexusFunction::nxgetattrainfo)(NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
Definition at line 68 of file napi_internal.h.
Referenced by NXgetattrainfo().
NXstatus(* NexusFunction::nxgetattrinfo)(NXhandle handle, int *no_items)
Definition at line 69 of file napi_internal.h.
Referenced by NXgetattrinfo().
NXstatus(* NexusFunction::nxgetdata)(NXhandle handle, void *data)
Definition at line 60 of file napi_internal.h.
Referenced by NXgetdata(), and NXgetinfo64().
NXstatus(* NexusFunction::nxgetdataID)(NXhandle handle, NXlink *pLink)
Definition at line 57 of file napi_internal.h.
Referenced by NXgetdataID().
NXstatus(* NexusFunction::nxgetgroupID)(NXhandle handle, NXlink *pLink)
Definition at line 70 of file napi_internal.h.
Referenced by NXgetgroupID().
NXstatus(* NexusFunction::nxgetgroupinfo)(NXhandle handle, int *no_items, NXname name, NXname nxclass)
Definition at line 71 of file napi_internal.h.
NXstatus(* NexusFunction::nxgetinfo64)(NXhandle handle, int *rank, int64_t dimension[], int *datatype)
Definition at line 61 of file napi_internal.h.
Referenced by NXgetdata().
NXstatus(* NexusFunction::nxgetnextattr)(NXhandle handle, NXname pName, int *iLength, int *iType)
Definition at line 64 of file napi_internal.h.
NXstatus(* NexusFunction::nxgetnextattra)(NXhandle handle, NXname pName, int *rank, int dim[], int *iType)
Definition at line 65 of file napi_internal.h.
Referenced by NXgetnextattra().
NXstatus(* NexusFunction::nxgetnextentry)(NXhandle handle, NXname name, NXname nxclass, int *datatype)
Definition at line 62 of file napi_internal.h.
NXstatus(* NexusFunction::nxgetslab64)(NXhandle handle, void *data, const int64_t start[], const int64_t size[])
Definition at line 63 of file napi_internal.h.
NXstatus(* NexusFunction::nxinitattrdir)(NXhandle handle)
Definition at line 74 of file napi_internal.h.
Referenced by NXinitattrdir().
NXstatus(* NexusFunction::nxinitgroupdir)(NXhandle handle)
Definition at line 73 of file napi_internal.h.
Referenced by NXinitgroupdir().
NXstatus(* NexusFunction::nxmakedata64)(NXhandle handle, CONSTCHAR *label, int datatype, int rank, int64_t dim[])
Definition at line 48 of file napi_internal.h.
NXstatus(* NexusFunction::nxmakegroup)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
Definition at line 45 of file napi_internal.h.
Referenced by NXlinkexternal().
NXstatus(* NexusFunction::nxmakelink)(NXhandle handle, NXlink *pLink)
Definition at line 58 of file napi_internal.h.
Referenced by NXmakelink().
NXstatus(* NexusFunction::nxmakenamedlink)(NXhandle handle, CONSTCHAR *newname, NXlink *pLink)
Definition at line 59 of file napi_internal.h.
NXstatus(* NexusFunction::nxnativeexternallink)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *externalfile, CONSTCHAR *remotetarget)
Definition at line 77 of file napi_internal.h.
Referenced by NXlinkexternal(), and NXlinkexternaldataset().
NXstatus(* NexusFunction::nxnativeinquirefile)(NXhandle handle, char *externalfile, const int filenamelength)
Definition at line 78 of file napi_internal.h.
Referenced by NXinquirefile().
NXstatus(* NexusFunction::nxnativeisexternallink)(NXhandle handle, CONSTCHAR *name, char *url, int urllen)
Definition at line 79 of file napi_internal.h.
Referenced by NXisexternaldataset(), and NXisexternalgroup().
NXstatus(* NexusFunction::nxopendata)(NXhandle handle, CONSTCHAR *label)
Definition at line 51 of file napi_internal.h.
Referenced by NXisexternaldataset(), NXlinkexternaldataset(), and NXopendata().
NXstatus(* NexusFunction::nxopengroup)(NXhandle handle, CONSTCHAR *name, CONSTCHAR *NXclass)
Definition at line 46 of file napi_internal.h.
Referenced by NXisexternalgroup(), NXlinkexternal(), and NXopengroup().
NXstatus(* NexusFunction::nxprintlink)(NXhandle handle, NXlink *link)
Definition at line 76 of file napi_internal.h.
Referenced by NXIprintlink().
NXstatus(* NexusFunction::nxputattr)(NXhandle handle, CONSTCHAR *name, const void *data, int iDataLen, int iType)
Definition at line 54 of file napi_internal.h.
NXstatus(* NexusFunction::nxputattra)(NXhandle handle, CONSTCHAR *name, const void *data, const int rank, const int dim[], const int iType)
Definition at line 55 of file napi_internal.h.
Referenced by NXputattra().
NXstatus(* NexusFunction::nxputdata)(NXhandle handle, const void *data)
Definition at line 53 of file napi_internal.h.
Referenced by NXputdata().
NXstatus(* NexusFunction::nxputslab64)(NXhandle handle, const void *data, const int64_t start[], const int64_t size[])
Definition at line 56 of file napi_internal.h.
NXstatus(* NexusFunction::nxreopen)(NXhandle pOrigHandle, NXhandle *pNewHandle)
Definition at line 42 of file napi_internal.h.
Referenced by NXreopen().
NXstatus(* NexusFunction::nxsameID)(NXhandle handle, NXlink *pFirstID, NXlink *pSecondID)
Definition at line 72 of file napi_internal.h.
NXstatus(* NexusFunction::nxsetnumberformat)(NXhandle handle, int type, char *format)
Definition at line 75 of file napi_internal.h.
Referenced by NXsetnumberformat().
NXhandle NexusFunction::pNexusData
Definition at line 41 of file napi_internal.h.
Referenced by NXclose(), NXclosedata(), NXclosegroup(), NXcompmakedata64(), NXcompress(), NXflush(), NXgetattr(), NXgetattra(), NXgetattrainfo(), NXgetattrinfo(), NXgetdata(), NXgetdataID(), NXgetgroupID(), NXgetgroupinfo(), NXgetinfo64(), NXgetnextattr(), NXgetnextattra(), NXgetnextentry(), NXgetrawinfo(), NXgetrawinfo64(), NXgetslab64(), NXinitattrdir(), NXinitgroupdir(), NXinquirefile(), NXIprintlink(), NXisexternaldataset(), NXisexternalgroup(), NXlinkexternal(), NXlinkexternaldataset(), NXmakedata64(), NXmakegroup(), NXmakelink(), NXmakenamedlink(), NXopendata(), NXopengroup(), NXputattr(), NXputattra(), NXputdata(), NXputslab64(), NXreopen(), NXsameID(), and NXsetnumberformat().
int NexusFunction::stripFlag
Definition at line 80 of file napi_internal.h.
Referenced by NXgetdata(), and NXgetinfo64().
The documentation for this struct was generated from the following file:
/isis/nexus_temp/include/napi_internal.h