#!/usr/bin/env python
"""
   Generate the DocBook header for the 
   NeXus manual section identified in sys.argv[1]
   Section classes are supplied in sys.argv[2:]
"""

########### SVN repository information ###################
# $Date: 2008$
# $Author$
# $Revision$
# $HeadURL$
# $Id$
########### SVN repository information ###################

import sys

category = sys.argv[1]
classes = sys.argv[2:]

xref = {}
xref['base'] = "base classes"
xref['application'] = "application definitions"
xref['contributed'] = "contributed definitions"
secondary = xref[category.lower()]

print '<?xml version="1.0" encoding="UTF-8"?>'
print '<?oxygen RNGSchema="http://www.oasis-open.org/docbook/xml/5.0/rng/docbook.rng" type="xml"?>'
print '<!-- autogenerated from the Makefile, do NOT edit this file -->'
print '<!-- autogenerated from the Makefile, do NOT put in version control -->'
print '<section xml:id="ClassDefinitions-%s" version="5.0" xmlns="http://docbook.org/ns/docbook" xmlns:xi="http://www.w3.org/2001/XInclude">' % category
print '  <title>NeXus %s Classes</title>' % category
print '  <indexterm significance="preferred"><primary>classes</primary><secondary>%s</secondary></indexterm>' % secondary
print '  <para>A description of each NeXus %s Class is given.</para>' % category
if len(classes) == 0:
	print '  <para>No NeXus %s Classes were defined at the time this version of the manual was created.</para>' % category
else:
	for item in classes:
		cl = item.split("/")[1]
		print '  <xi:include href="%s" />' % cl
print '</section>'

