category: base
doc: |
  Base class to store the configuration when using the MTex/Matlab software.
  
  MTex is a Matlab package for texture analysis used in the Materials and Earth Sciences.
  See `R. Hielscher et al. <https://mtex-toolbox.github.io/publications>`_ and
  the `MTex source code <https://github.com/mtex-toolbox>`_ for details.
type: group
NXms_mtex_config(NXobject):
  conventions(NXcollection):
    doc: |
      Reference frame and orientation conventions.
      Consult the `MTex docs <https://mtex-toolbox.github.io/EBSDReferenceFrame.html>`_ for details.
    x_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
      # enumeration:
    # check against v5.12
    z_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
      # enumeration:
    a_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
      # enumeration:
    b_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
      # enumeration:
    euler_angle(NX_CHAR):
      doc: |
        TODO with MTex developers
      enumeration: [unknown, undefined, bunge]
  plotting(NXcollection):
    doc: |
      Settings relevant for generating plots.
    font_size(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY
    inner_plot_spacing(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY
    outer_plot_spacing(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY
    marker_size(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY
    figure_size(NX_NUMBER):
      doc: |
        TODO with MTex developers
    show_micron_bar(NX_BOOLEAN):
      doc: |
        True if MTex renders a scale bar with figures.
    show_coordinates(NX_BOOLEAN):
      doc: |
        True if MTex renders a grid with figures.
    pf_anno_fun_hdl:
      doc: |
        Code for the function handle used for annotating pole figure plots.
    color_map(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_UNITLESS
      dim: (i, 3)
    default_color_map(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_UNITLESS
      dim: (i, 3)
    # phase_color_order:
    #   doc: |
    #     TODO with MTex developers
    #   unit: NX_UNITLESS
    #   dim: (i,)
    color_palette(NX_CHAR):
    degree_char(NX_CHAR):
      doc: |
        TODO with MTex developers
    arrow_char(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker_edge_color(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker_face_color(NX_CHAR):
      doc: |
        TODO with MTex developers
    hit_test(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
  miscellaneous(NXcollection):
    doc: |
      Miscellaneous other settings of MTex.
    mosek(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    generating_help_mode(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    methods_advise(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    stop_on_symmetry_mismatch(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    inside_poly(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    text_interpreter:
  numerics(NXcollection):
    doc: |
      Miscellaneous settings relevant for numerics.
    eps(NX_NUMBER):
      doc: |
        Return value of the Matlab eps command.
      unit: NX_UNITLESS
    fft_accuracy(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY  # NX_LENGTH or NX_RECIPROCAL_LENGTH?
    max_stwo_bandwidth(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY  # radiant?
    max_sothree_bandwidth(NX_NUMBER):
      doc: |
        TODO with MTex developers
      unit: NX_ANY  # radiant?
  system(NXcollection):
     doc: |
       Miscellaneous settings relevant of the system where MTex runs.
     memory(NX_NUMBER):
       doc: |
         TODO with MTex developers
     open_gl_bug(NX_BOOLEAN):
       doc: |
         TODO with MTex developers
     save_to_file(NX_BOOLEAN):
       doc: |
         TODO with MTex developers
  path(NXcollection):
    doc: |
      Collection of paths from where MTex reads information and code.
    mtex(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    data(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    cif(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    ebsd(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    pf(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    odf(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    tensor(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    example(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    import_wizard(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    pf_extensions(NX_CHAR):
      doc: |
        List of file type suffixes for which MTex assumes
        texture/pole figure information.
    ebsd_extensions(NX_CHAR):
      doc: |
        List of file type suffixes for which MTex assumes EBSD content.
    # version as an instance of (NXprogram) one for MTex one for Matlab
