#!/bin/sh
latest_r=`/usr/bin/svnlook youngest /isis/svn/nexus/code`
var=`ls -t nexus-4.4*.tar.gz | head -1`
current_r=`echo $var | sed -e 's/.*svn\([0-9]*\)\.tar\.gz/\1/'`
if test $latest_r -gt $current_r; then
    echo "<P><B>WARNING</B>: The files below correspond to svn revision <B>${current_r}</B> which is now out of date; files for revision <B>${latest_r}</B> are currently being built and will be automatically posted here within the next hour at most.</B></P>"
fi
cd rpm
rpm386=`ls -t nexus-4.4*.i386.rpm | head -1`
rpmx64=`ls -t nexus-4.4*.x86_64.rpm | head -1`
srcrpm=`ls -t nexus-4.4*.src.rpm | head -1`
cd ..
echo "<UL>"
echo "<LI><A HREF=\"$var\">Source distribution ($var)</A>&nbsp;"
echo "<LI><A HREF=\"rpm/$srcrpm\">Linux (Fedora) RPM source distribution ($srcrpm)</A>&nbsp;"
echo "<LI><A HREF=\"rpm/$rpm386\">Linux (Fedora) i386 binary RPM ($rpm386)</A>&nbsp;"
echo "<LI><A HREF=\"rpm/$rpmx64\">Linux (Fedora) x86_64 binary RPM ($rpmx64)</A>&nbsp;"
echo "</UL>"
