name: Deploy HTML to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create basic index.html
        run: |
          mkdir public
          echo "<html><head><title>Definitions</title></head><body>" > public/index.html
          echo "<h1>Definitions Files</h1><ul>" >> public/index.html
          find . -name "*.json" | sort | while read file; do
            echo "<li><a href='https://github.com/${{ github.repository }}/blob/main/$file'>$file</a></li>" >> public/index.html
          done
          echo "</ul></body></html>" >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
