name: Syntax Checks

on: [push]

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment:
            anaconda-test-env-py-${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: true
        channels: defaults,conda-forge
        # environment-file: environment.yml
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true  # required for caching
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        conda env list
        printenv | sort

    # $CONDA is an environment variable pointing to the
    # root of the miniconda directory

    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file .github/env-workflow.yml --name $ENV_NAME
        $CONDA/bin/conda list -r --name $ENV_NAME
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Run tests
      run: |
        source $CONDA/bin/activate $ENV_NAME
        # pytest -vvv ./utils/test_suite.py
        python ./utils/test_suite.py
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Build the documentation
      run: |
        source $CONDA/bin/activate $ENV_NAME
        make makebuilddir
        pushd build/manual
        # CI needs latexmk to execute next line
        # make latexpdf && cp build/latex/nexus.pdf build/html/NeXusManual.pdf
        cd build
        tar czf ../../../docs.tar.gz html
        popd
        ls -lAGh
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}
